### PR TITLE
Added note about correct ros2_tracing branch

### PR DESCRIPTION
**Pull request by nightduck**
This repo doesn't support ROS2 rolling release. Following the readme verbatim will result in trying build the latest version of ros2_tracing, which will fail. I added a note that the developer should checkout galactic instead

### CODE REVIEW

**Comment by christophebedard** [comment]
How does the latest version of `ros2_tracing` fail? Can you share the error? I don't think it shoudl fail.

**Comment by christophebedard** [comment]
This repo *should* support Rolling. If it doesn't, then we shoudl fix it.

**Comment by flynneva** [comment]
> This repo doesn't support ROS2 rolling release.

@nightduck so this is a super bad month to be using anything `rolling` related as [they are transitioning to a brand new OS (Ubuntu 22.04](https://discourse.ros.org/t/preparing-ros-2-rolling-for-the-transition-to-ubuntu-22-04/23124) I think next week (?) but I could be wrong. So by the end of the month `rolling` will no longer work on `Ubuntu 20.04 Focal`.

>  trying build the latest version of ros2_tracing, which will fail

@nightduck as @christophebedard points out the failure isn't caused by `ros2_tracing`, but rather a temporary patch for [an upstream `rosidl_python` bug](https://github.com/ros-realtime/reference-system/pull/96) that was [recently fixed in `rolling`](https://github.com/ros2/rosidl_python/pull/125).

We should be able to remove this patch and get `rolling` to be back up and running, however we should be careful to also continue to support older distros since many people are not using `rolling`.

Also, as a side note and fyi to @christophebedard I am about to push a big update to this repo's testing framework migrating away from the crazy cmake logic to a more reusable and test-able python framework we have been working on. Hoping to make a PR over the weekend for this actually.

**Comment by christophebedard** [comment]
> So by the end of the month rolling will no longer work on Ubuntu 20.04 Focal.

just a small clarification: Ubuntu 20.04 will be supported as a tier 3 platform for Rolling, at least during Humble/before the next release: https://www.ros.org/reps/rep-2000.html#humble-hawksbill-may-2022-may-2027

> We should be able to remove this patch and get rolling to be back up and running, however we should be careful to also continue to support older distros since many people are not using rolling.

We could find a way to have this workaround only apply to Galactic and earlier.

**Comment by nightduck** [comment]
> How does the latest version of `ros2_tracing` fail? Can you share the error? I don't think it should fail.

When building latest ros2_tracing against galactic binaries, I get the following errors:

```
--- stderr: test_tracetools                              
/workspace/src/ros2_tracing/test_tracetools/src/test_lifecycle_client.cpp: In member function ‘unsigned int LifecycleNodeClient::get_state(std::chrono::seconds)’:
/workspace/src/ros2_tracing/test_tracetools/src/test_lifecycle_client.cpp:84:73: error: ‘using SharedFuture = class std::shared_future<std::shared_ptr<lifecycle_msgs::srv::GetState_Response_<std::allocator<void> > > >’ {aka ‘class std::shared_future<std::shared_ptr<lifecycle_msgs::srv::GetState_Response_<std::allocator<void> > > >’} has no member named ‘future’
   84 |     auto future_result = client_get_state_->async_send_request(request).future.share();
      |                                                                         ^~~~~~
/workspace/src/ros2_tracing/test_tracetools/src/test_lifecycle_client.cpp: In member function ‘bool LifecycleNodeClient::change_state(uint8_t, bool, std::chrono::seconds)’:
/workspace/src/ros2_tracing/test_tracetools/src/test_lifecycle_client.cpp:128:76: error: ‘using SharedFuture = class std::shared_future<std::shared_ptr<lifecycle_msgs::srv::ChangeState_Response_<std::allocator<void> > > >’ {aka ‘class std::shared_future<std::shared_ptr<lifecycle_msgs::srv::ChangeState_Response_<std::allocator<void> > > >’} has no member named ‘future’
  128 |     auto future_result = client_change_state_->async_send_request(request).future.share();
```

Pretty run-of-the-mill api change stuff. But as @christophebedard  mentioned in my other issue, removing the rosidl_python workaround in this repo should allow us to build against rolling (I haven't confirmed). In which case, there's no need for this note. The latest version of `ros2_tracing` builds fine against ROS2 rolling.

**Comment by christophebedard** [comment]
ahh okay I see!

File: autoware_reference_system/README.md [hunk 1]
```diff
@@ -144,6 +144,7 @@ Before running the tests there are a few prerequisites to complete:
 - Install LTTng and `ros2_tracing` [following the instructions in `ros2_tracing`](https://gitlab.com/ros-tracing/ros2_tracing#building)
    - _Note:_ if you are setting up [ a realtime linux kernel for a raspberry pi using this docker file](https://github.com/ros-realtime/rt-kernel-docker-builder#raspberry-pi-4-rt-linux-kernel), it should [already include LTTng](https://github.com/ros-realtime/rt-kernel-docker-builder/pull/18)
    - _Note:_ make sure to clone `ros2_tracing` into **the same workspace as where you put the `reference-system`**, the tests will not properly run if they are not in the same directory.
+   - _Note:_ be sure to clone the correct branch of `ros2_tracing`. As of press time, this repo doesn't support the rolling release, so check out galactic with `git clone -b galactic https://gitlab.com/ros-tracing/ros2_tracing.git`
```
Comment (flynneva) [inline autoware_reference_system/README.md:147]: @nightduck I think this line should just be:

>>>
Ensure to checkout the matching `ros2_tracing` branch for the ROS 2 distro that is being used (e.g. if using `galactic`, checkout the `ros2_tracing` `galactic` branch)
>>>

**Comment by nightduck** [comment]
Rephrased. But I still vote to close this PR without merging, if #98 and #96 get pulled. I only added this note to gently guide users away from building against rolling. If that pitfall is removed, this addition only clutters the README

**Comment by flynneva** [comment]
@nightduck with #99 merged and your above comment I'll go ahead and close this without merging. Ping me if you want to reopen it though
